name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_NAME: iptv-channels
  DOCKERHUB_REPO: bf963/iptv-channels

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.6.0

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Login to DockerHub
      uses: docker/login-action@v3.4.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: ${{ env.DOCKERHUB_REPO }}:latest
